### ISSUE TITLE
Adding a label causes failure at runtime

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-java#127]
Using 1.12.0, adding a label to a function causes a runtime failure. To repro, run `mvn tests` here https://github.com/esara/quarkus-super-heroes/tree/logger-error .

```
java.lang.ClassCastException: class com.sun.proxy.$Proxy90 cannot be cast to class com.appland.appmap.annotation.Labels (com.sun.proxy.$Proxy90 is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @6cb2b947; com.appland.appmap.annotation.Labels is in unnamed module of loader 'app')
	at com.appland.appmap.output.v1.CodeObject.<init>(CodeObject.java:189)
	at com.appland.appmap.output.v1.CodeObject.createTree(CodeObject.java:337)
	at com.appland.appmap.record.EventTemplateRegistry.register(EventTemplateRegistry.java:50)
	at com.appland.appmap.record.EventTemplateRegistry.register(EventTemplateRegistry.java:39)
	at com.appland.appmap.transform.annotations.Hook.prepare(Hook.java:116)
	at com.appland.appmap.transform.ClassFileTransformer.lambda$applyHooks$1(ClassFileTransformer.java:116)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.appland.appmap.transform.ClassFileTransformer.applyHooks(ClassFileTransformer.java:118)
	at com.appland.appmap.transform.ClassFileTransformer.transform(ClassFileTransformer.java:178)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:454)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:414)
	at io.quarkus.workshop.superheroes.fight.FightService_Bean.<init>(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans3(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:118)
	at io.quarkus.arc.Arc.initialize(Arc.java:24)
	at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:40)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources686947423.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources686947423.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
```

**Comment by apotterri** [comment]
This was fixed by moving `Labels` into `appmap-annotation`.
