### ISSUE TITLE
Mocking SQL Statement causes test to fail, when using AppMap Maven plugin

### ISSUE THREAD

**Issue by sualeh** [applandinc/appmap-java#129]
I am using the AppMap Maven plugin to instrument my builds. I have a JUnit test that forces an error in the execution of a SQL query. The test is set up with Mockito like this:

```java
Statement statement = mock(Statement.class);
when(statement.execute(anyString()))
  .thenThrow(new SQLException("Exception executing SQL statement"));
```

My build fails when AppMap tries to introspect the database name. The code at `com.appland.appmap.process.hooks.SqlQuery.getDbName(SqlQuery.java:47)` expects a `SQLException`, but an `InvalidUseOfMatchersException` exception is thrown instead, failing the build. More details are in the stack trace below. 

```
[ERROR] us.fatehi.utility.test.DatabaseUtilityTest.executeSql_throw  Time elapsed: 0.433 s  <<< ERROR!
org.mockito.exceptions.misusing.InvalidUseOfMatchersException:

Invalid use of argument matchers!
0 matchers expected, 1 recorded:
-> at us.fatehi.utility.test.DatabaseUtilityTest.executeSql_throw(DatabaseUtilityTest.java:147)

This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(any(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(any(), eq("String by matcher"));

For more info see javadoc for Matchers class.

        at com.appland.appmap.process.hooks.SqlQuery.getDbName(SqlQuery.java:47)
        at com.appland.appmap.process.hooks.SqlQuery.recordSql(SqlQuery.java:61)
        at com.appland.appmap.process.hooks.SqlQuery.execute(SqlQuery.java:122)
        at us.fatehi.utility.test.DatabaseUtilityTest.executeSql_throw(DatabaseUtilityTest.java:147)
		...
```

**Comment by sualeh** [comment]
@apotterri @dustinbyrne - thanks for the new release. I will give it a spin.
